### ISSUE TITLE
Indexer snapshots don't work in GKE anymore

### ISSUE THREAD

**Issue by AlexGilleran** [TerriaJS/magda#167]
```
Caused by: RemoteTransportException[[JLq_IH-][10.48.6.11:9300][cluster:admin/snapshot/create]]; nested: RepositoryMissingException[[snapshots] missing];
Caused by: RepositoryMissingException[[snapshots] missing]
	at org.elasticsearch.repositories.RepositoriesService.repository(RepositoriesService.java:334)
	at org.elasticsearch.snapshots.SnapshotsService.createSnapshot(SnapshotsService.java:226)
	at org.elasticsearch.action.admin.cluster.snapshots.create.TransportCreateSnapshotAction.masterOperation(TransportCreateSnapshotAction.java:82)
	at org.elasticsearch.action.admin.cluster.snapshots.create.TransportCreateSnapshotAction.masterOperation(TransportCreateSnapshotAction.java:41)
	at org.elasticsearch.action.support.master.TransportMasterNodeAction.masterOperation(TransportMasterNodeAction.java:87)
	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$2.doRun(TransportMasterNodeAction.java:166)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

>:(

**Comment by AlexGilleran** [comment]
* Sometimes they work.

**Comment by tkeuneman** [comment]
All good, no longer relevant.
