### ISSUE TITLE
Feedback API CSP endpoint reports 500 error

### ISSUE THREAD

**Issue by t83714** [TerriaJS/magda#742]
Encounter this error while testing my local dev env in minikube.
```
TypeError: Cannot read property 'document-uri' of undefined
    at formatCspReportBody (/usr/src/app/component/dist/buildFeedbackRouter.js:33:24)
    at /usr/src/app/component/dist/buildFeedbackRouter.js:14:19
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/src/app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at /usr/src/app/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
    at jsonParser (/usr/src/app/component/node_modules/body-parser/lib/types/json.js:118:7)
```

**Comment by t83714** [comment]
It seems chrome will send Conent-Type=application/csp-report and that will cause the issue
